export const SET_USER = 'SET_USER'
export const SET_EMAIL = 'SET_EMAIL'
export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const SET_TOKEN = 'SET_TOKEN'

export const FETCHING_USERDATA_REQUESTED = 'FETCHING_USERDATA_REQUESTED'
export const FETCHING_USERDATA_SUCCESS = 'FETCHING_USERDATA_SUCCESS'
export const FETCHING_USERDATA_FAILURE = 'FETCHING_USERDATA_FAILURE'

export const FETCHING_PCRITERIA_SUCCESS = 'FETCHING_PCRITERIA_SUCCESS'

