export const LOGIN_REQUESTED = 'LOGIN_REQUESTED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_USER = 'LOGOUT_USER'
export const RENEW_TOKEN = 'RENEW_TOKEN'
export const CLEAR_LOG_IN_MESSAGE = 'CLEAR_LOG_IN_MESSAGE'



export const SIGNUP_REQUESTED = 'SIGNUP_REQUESTED'
	export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
	export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'